apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
      color: green
  template:
    metadata:
      labels:
        app: nodejs
        color: green
    spec:
      containers:
      - name: nodejs
        image: <your-dockerhub-username>/bluegreen-app:latest
        ports:
        - containerPort: 3000
