apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
    version: blue # Starts with blue version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer