controller:
  serviceType: LoadBalancer
  servicePort: 80
  jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local"
  installPlugins:
    - kubernetes:1.31.6
    - workflow-aggregator:2.6
    - git:4.11.3
    - blueocean:1.25.7
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  javaOpts: "-Xms1g -Xmx2g -Djenkins.install.runSetupWizard=false"
  adminUser: "admin"
  adminPassword: "admin"

persistence:
  enabled: true
  size: "10Gi"

agent:
  enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"